(require 'auto-complete)
(require 'auto-complete-config)
(setq ac-auto-start t)
(global-auto-complete-mode t)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/elpa/auto-complete-1.4/dict")
(ac-config-default)
(ac-set-trigger-key "TAB")
(add-hook 'before-save-hook 'delete-trailing-whitespace)
